import '../models/product.dart';

final List<Product> mockProducts = [
  // Fruits
  Product(
    id: 'p1',
    titre: 'Pommes Golden',
    description: 'Pommes croquantes et sucrées.',
    prix: 3.0,
    stock: 50,
    photo: 'assets/pomme golden.jpg',
    categorie: 'Fruits',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p2',
    titre: 'Bananes Plantain',
    description: 'Bananes mûres, parfaites pour la cuisson.',
    prix: 2.2,
    stock: 80,
    photo: 'assets/banane plantain.jpg',
    categorie: 'Fruits',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p3',
    titre: 'Mangues Kent',
    description: 'Mangues juteuses et parfumées.',
    prix: 4.5,
    stock: 30,
    photo: 'assets/Mange Kent.jpg',
    categorie: 'Fruits',
    producteurId: '3',
    statut: 'actif',
  ),
  // Légumes
  Product(
    id: 'p4',
    titre: 'Tomates fraîches',
    description: 'Tomates bio, cultivées localement.',
    prix: 2.5,
    stock: 100,
    photo: 'assets/tomate fraiche.jpg',
    categorie: 'Légumes',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p5',
    titre: 'Carottes Nouvelles',
    description: 'Carottes croquantes, riches en vitamines.',
    prix: 2.0,
    stock: 60,
    photo: 'assets/Carrots.jpg',
    categorie: 'Légumes',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p6',
    titre: 'Salade Verte',
    description: 'Salade fraîche, idéale pour vos entrées.',
    prix: 1.5,
    stock: 40,
    photo: 'assets/salade verte.jpg',
    categorie: 'Légumes',
    producteurId: '3',
    statut: 'actif',
  ),
  // Céréales
  Product(
    id: 'p7',
    titre: 'Maïs Jaune',
    description: 'Maïs doux, parfait pour grillades.',
    prix: 1.8,
    stock: 70,
    photo: 'assets/maïs jaune.jpg',
    categorie: 'Céréales',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p8',
    titre: 'Riz Local',
    description: 'Riz blanc local, grains longs.',
    prix: 2.7,
    stock: 120,
    photo: 'assets/riz local.jpg',
    categorie: 'Céréales',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p9',
    titre: 'Mil',
    description: 'Mil traditionnel, riche en fibres.',
    prix: 2.3,
    stock: 90,
    photo: 'assets/mil.jpg',
    categorie: 'Céréales',
    producteurId: '3',
    statut: 'actif',
  ),
  // Tubercules
  Product(
    id: 'p10',
    titre: 'Pommes de Terre',
    description: 'Pommes de terre fermes, parfaites pour la cuisson.',
    prix: 1.9,
    stock: 110,
    photo: 'assets/Pomme de terre.jpg',
    categorie: 'Tubercules',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p11',
    titre: 'Patates Douces',
    description: 'Patates douces sucrées, riches en bêta-carotène.',
    prix: 2.4,
    stock: 75,
    photo: 'assets/patate douce.jpg',
    categorie: 'Tubercules',
    producteurId: '3',
    statut: 'actif',
  ),
  Product(
    id: 'p12',
    titre: 'Manioc',
    description: 'Manioc frais, idéal pour l’attiéké.',
    prix: 2.1,
    stock: 60,
    photo: 'assets/Manioc.jpg',
    categorie: 'Tubercules',
    producteurId: '3',
    statut: 'actif',
  ),
]; 